# Generated by Django 4.1 on 2022-08-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buttle',
            new_name='Bottle',
        ),
    ]
