# Generated by Django 4.1.1 on 2022-10-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_order_client_alter_client_user'),
        ('core', '0002_rename_buttle_bottle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='address',
        ),
        migrations.AddField(
            model_name='bottle',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='bottels', to='clients.order', verbose_name='Заказы'),
        ),
    ]
