# Generated by Django 4.1.1 on 2022-10-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_order_client_alter_client_user'),
        ('core', '0004_alter_bottle_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='bottles', to='clients.order', verbose_name='Заказы'),
        ),
    ]
