# Generated by Django 4.1.1 on 2022-09-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('is_acteve', models.DateField(default=True, verbose_name='Является активным покупателем')),
                ('bottles', models.IntegerField(default=1)),
            ],
        ),
    ]
