# Generated by Django 4.1.1 on 2022-09-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_acteve',
            field=models.BooleanField(default=True, verbose_name='Является активным покупателем'),
        ),
    ]
