# Generated by Django 4.1.1 on 2022-09-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='is_acteve',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
